# Generated by Django 4.2.6 on 2023-10-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='modal_image',
            field=models.ImageField(blank=True, null=True, upload_to='./templates/uploads'),
        ),
    ]
