# Generated by Django 4.2.6 on 2023-10-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('subscription_type', models.CharField(choices=[('Premium', 'Premium'), ('PremiumPlus', 'PremiumPlus')], default='PremiumPlus', max_length=30)),
                ('duration', models.PositiveIntegerField(default=7)),
                ('duration_period', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Weekly', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_in', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user_profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='home.userprofiles')),
            ],
        ),
    ]
