# Generated by Django 4.2.6 on 2023-10-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_period',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Free', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('Premium', 'Premium'), ('PremiumPlus', 'PremiumPlus'), ('Free', 'Free')], default='PremiumPlus', max_length=30),
        ),
    ]
