# Generated by Django 4.2.6 on 2023-11-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_subscription_duration_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_period',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Free ', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('Premium', 'Premium'), ('PremiumPlus', 'PremiumPlus'), ('Free', 'Free')], default='Free', max_length=30),
        ),
    ]
