# Generated by Django 4.2.6 on 2023-11-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_subscription_duration_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='number_of_votes',
            field=models.CharField(choices=[('5', '5'), ('8', '8'), ('3', '3')], default='Free', max_length=30),
        ),
    ]
