# Generated by Django 4.2.6 on 2023-11-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_subscription_number_of_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_period',
            field=models.CharField(choices=[('Three_Days', 'Three_Days'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Free ', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='number_of_votes',
            field=models.CharField(choices=[('5', '5'), ('3', '3'), ('8', '8')], default='Free', max_length=30),
        ),
    ]
