# Generated by Django 4.2.6 on 2023-11-06 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_subscription_number_of_votes_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payment'},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name_plural': 'PaymentHistory'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name_plural': 'Subscription'},
        ),
        migrations.AlterModelOptions(
            name='userprofiles',
            options={'verbose_name_plural': 'Userprofiles'},
        ),
        migrations.AlterModelOptions(
            name='usersubscriptions',
            options={'verbose_name_plural': 'UserSubscriptions'},
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='user_subscription',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='home.usersubscriptions'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='number_of_votes',
            field=models.CharField(choices=[('3', '3'), ('8', '8'), ('5', '5')], default='Free', max_length=30),
        ),
    ]
