# Generated by Django 4.2.6 on 2023-11-06 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_payment_options_alter_paymenthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.userprofiles'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='number_of_votes',
            field=models.CharField(choices=[('8', '8'), ('5', '5'), ('3', '3')], default='Free', max_length=30),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to='home.userprofiles'),
        ),
    ]
